"use client"

import * as React from "react"

export type AppLanguage = "et" | "en"

type Vars = Record<string, string | number>

const STORAGE_KEY = "claw.language.v1"

const EN: Record<string, string> = {
  "language.title": "Language",
  "language.description": "Choose the app language. The choice is saved on this device.",
  "language.et": "Eesti",
  "language.en": "English",
  "nav.home": "Home",
  "nav.chat": "Chat",
  "nav.terminal": "Terminal",
  "nav.approvals": "Approvals",
  "nav.settings": "Settings",
  "title.dashboard": "Dashboard",
  "title.chat": "Chat",
  "title.terminal": "Terminal",
  "title.approvals": "Approvals",
  "title.settings": "Settings",
  "title.seekclaw": "SeekClaw",
  "status.online": "Online",
  "status.offline": "Offline",
  "status.degraded": "Degraded",
  "status.unknown": "Unknown",
  "status.idle": "Not paired",
  "status.connecting": "Connecting",
  "status.error": "Error",
  "common.retry": "Retry",
  "common.repair": "Re-pair",
  "common.automatic": "Automatic",
  "common.requiresApproval": "Requires your approval",
  "common.clear": "Clear",
  "common.reconnect": "Reconnect",
  "connection.gatewayError": "Gateway error",
  "connection.gatewayOffline": "Gateway offline",
  "connection.paused": "Live data is paused until the gateway is reachable.",
  "connection.connectingTo": "Connecting to {name}…",
  "pair.kicker": "CLAW Bridge",
  "pair.title": "Pair with your Termux gateway",
  "pair.description": "Enter the gateway URL and the one-time pairing token printed by claw pair on your device.",
  "pair.gatewayUrl": "Gateway URL",
  "pair.gatewayHint": "LAN address or Tailscale hostname of the gateway.",
  "pair.gatewayInvalid": "Must start with http://, https://, ws:// or wss://",
  "pair.token": "Pairing token",
  "pair.tokenHint": "Stored only on this device.",
  "pair.failed": "Connection failed",
  "pair.connected": "Connected",
  "pair.opening": "Paired with {name}. Opening dashboard…",
  "pair.testing": "Testing connection…",
  "pair.connect": "Connect",
  "pair.recent": "Recent gateways",
  "pair.recentHint": "Tap to reuse a saved connection.",
  "theme.title": "Appearance",
  "theme.description": "Choose the CLAW display profile yourself. Auto is optional and never the default.",
  "theme.claw-red": "Default CLAW look for normal use.",
  "theme.night-ops": "Low-light green terminal palette for dark rooms.",
  "theme.amber-terminal": "Warm amber palette for comfortable night use.",
  "theme.daylight": "Bright background and hard contrast for direct daylight.",
  "theme.oled-black": "True black background with minimal glow for AMOLED displays.",
  "theme.auto": "Optional system-based switching. Manual themes remain the default behavior.",
  "dashboard.refresh": "Refresh status",
  "dashboard.gateway": "Gateway",
  "dashboard.termux": "Termux",
  "dashboard.androidDevice": "Android device",
  "dashboard.charging": "charging",
  "dashboard.activeRuns": "Active runs",
  "dashboard.pendingApprovals": "Pending approvals",
  "dashboard.seekclawHint": "Find work · score fit · build locally · approve external actions",
  "dashboard.newCommand": "New command",
  "dashboard.lastHeartbeat": "Last heartbeat {time}",
  "seek.marketplace": "Agent marketplace",
  "seek.agent": "SeekClaw Agent",
  "seek.agentOnline": "Agent Online",
  "seek.bridgeOffline": "Bridge Offline",
  "seek.available": "Available",
  "seek.matching": "Matching",
  "seek.active": "Active",
  "seek.credits": "Credits",
  "seek.reputation": "Reputation",
  "seek.findWork": "Find Work",
  "seek.activeJobs": "Active Jobs",
  "seek.earnings": "Earnings",
  "seek.pipeline": "Autonomous pipeline",
  "seek.pipelineHint": "Local work runs automatically. External or costly actions stop at CLAW Approval.",
  "seek.findSuitable": "Find suitable work",
  "seek.evaluate": "Evaluate capability and fit",
  "seek.apply": "Apply for the job",
  "seek.build": "Codex / Claude builds locally",
  "seek.tests": "Run local tests",
  "seek.remote": "Remote Windows / server writes",
  "seek.submit": "Submit final result",
  "seek.creditSpending": "Credit spending",
  "seek.selectedJob": "Selected job",
  "seek.selectedHint": "Paste a SeekClaw job ID. CLAW keeps apply and external actions behind approval.",
  "seek.jobId": "SeekClaw job ID",
  "seek.applyApproval": "Apply with approval",
  "seek.workLocally": "Work locally",
  "seek.test": "Test",
  "seek.stage": "Stage result",
  "seek.output": "Agent output",
  "seek.outputHint": "Latest SeekClaw / Codex activity",
  "seek.connectCli": "Connect SeekClaw CLI in the local runtime, then refresh.",
  "seek.reading": "Reading SeekClaw profile and open jobs…",
  "seek.findFailed": "Find work failed",
  "seek.applicationWaiting": "Application is waiting for CLAW Approval before SeekClaw receives it.",
  "seek.applicationDone": "Application command completed.",
  "seek.applicationFailed": "Application failed",
  "seek.workFailed": "Local work failed",
  "seek.testsFailed": "Tests failed",
  "seek.stageFailed": "Could not prepare submission",
  "seek.stagedNotice": "Submission is staged locally. SeekClaw's currently documented API does not expose a final job-delivery endpoint, so CLAW will not fake one.",
  "chat.ask": "Ask",
  "chat.once": "Once",
  "chat.default": "Default",
  "chat.currentContext": "Current context",
  "chat.sharedMemory": "CLAW shared memory",
  "chat.refreshContext": "Refresh shared context",
  "chat.noBranch": "no branch",
  "chat.goal": "Goal",
  "chat.noGoal": "No project goal saved yet. Save a plan below and every agent gets it automatically.",
  "chat.latestFrom": "Latest from {executor}",
  "chat.changedFiles": "{count} changed files",
  "chat.agentOutput": "Agent output",
  "chat.gatewayOffline": "Gateway offline",
  "chat.sharedReady": "Shared context ready",
  "chat.reconnectContinue": "Reconnect to continue.",
  "chat.readyHint": "Plan here, then send it to Codex or Claude without starting from zero.",
  "chat.sendTo": "Send to",
  "chat.permission": "Permission",
  "chat.placeholder": "Plan here. CLAW will pass the shared context to the selected agent.",
  "chat.savePlan": "Save plan",
  "chat.stop": "Stop",
  "chat.sendContext": "Send with context",
  "chat.clearOutput": "Clear output",
  "chat.planSaved": "Plan saved to CLAW memory",
  "chat.runStopped": "Run stopped",
  "approvals.denied": "Denied",
  "approvals.allowedOnce": "Allowed once",
  "approvals.alwaysAllowed": "Always allowed",
  "approvals.justNow": "just now",
  "approvals.minutesAgo": "{count}m ago",
  "approvals.hoursAgo": "{count}h ago",
  "approvals.daysAgo": "{count}d ago",
  "approvals.risk": "{level} risk",
  "approvals.requested": "Requested {time}",
  "approvals.deny": "Deny",
  "approvals.allowOnce": "Allow once",
  "approvals.alwaysAllow": "Always allow",
  "approvals.pending": "Pending",
  "approvals.audit": "Audit history",
  "approvals.loadFailed": "Could not load approvals",
  "approvals.none": "Nothing to approve",
  "approvals.newHere": "New requests from agents will show up here.",
  "approvals.syncLater": "Approvals sync when the gateway is back online.",
  "approvals.noDecisions": "No decisions yet",
  "approvals.recorded": "Every allow or deny is recorded here.",
  "terminal.sessions": "Sessions",
  "terminal.close": "Close {name}",
  "terminal.newSession": "New session",
  "terminal.noSession": "No session",
  "terminal.createSession": "Create a session to start typing.",
  "terminal.running": "running",
  "terminal.input": "Terminal input",
  "terminal.typeCommand": "type a command",
  "terminal.gatewayOffline": "gateway offline",
  "terminal.send": "Send",
  "terminal.previous": "Previous command",
  "terminal.next": "Next command",
  "terminal.reconnected": "Session reconnected",
  "terminal.history": "History",
  "terminal.commandHistory": "Command history",
  "biometric.locked": "CLAW Bridge locked",
  "biometric.hint": "Use your screen lock or fingerprint to continue.",
  "biometric.checking": "Checking…",
  "biometric.unlock": "Unlock",
  "settings.gateway": "Gateway",
  "settings.pairedWith": "Paired with {name}",
  "settings.notPaired": "Not paired",
  "settings.gatewayUrl": "Gateway URL",
  "settings.gatewayChangeHint": "Changing the URL requires pairing again.",
  "settings.urlSaved": "Gateway URL saved. Re-pair to apply.",
  "settings.telegram": "Telegram bot",
  "settings.telegramHint": "Remote notifications and commands",
  "settings.termuxApi": "Termux:API",
  "settings.termuxApiHint": "Device sensors, clipboard, notifications",
  "settings.shizuku": "Shizuku",
  "settings.shizukuHint": "Elevated ADB-level access",
  "settings.security": "Security & notifications",
  "settings.biometric": "Biometric lock",
  "settings.biometricHint": "Require Android screen lock or fingerprint to open the app.",
  "settings.biometricEnabled": "Biometric lock enabled",
  "settings.notifications": "Notifications",
  "settings.notificationsHint": "Alert on new approval requests and finished runs.",
  "settings.permissions": "Permission defaults",
  "settings.permissionsHint": "Pre-selected values for new commands.",
  "settings.defaultTarget": "Default target",
  "settings.defaultMode": "Default permission mode",
  "settings.askEvery": "Ask every time",
  "settings.allowOnce": "Allow once",
  "settings.projectDefault": "Project default",
  "settings.autoAllow": "Auto-allow low risk",
  "settings.autoAllowHint": "Skip approval prompts for read-only commands.",
  "settings.backup": "Backup",
  "settings.backupHint": "Tokens are never included in exports.",
  "settings.export": "Export JSON",
  "settings.import": "Import JSON",
  "settings.unpair": "Unpair device",
  "settings.unpaired": "Unpaired from gateway"
}

const ET: Record<string, string> = {
  "language.title": "Keel",
  "language.description": "Vali rakenduse keel. Valik salvestatakse sellesse seadmesse.",
  "language.et": "Eesti",
  "language.en": "English",
  "nav.home": "Avaleht",
  "nav.chat": "Vestlus",
  "nav.terminal": "Terminal",
  "nav.approvals": "Kinnitused",
  "nav.settings": "Seaded",
  "title.dashboard": "Töölaud",
  "title.chat": "Vestlus",
  "title.terminal": "Terminal",
  "title.approvals": "Kinnitused",
  "title.settings": "Seaded",
  "title.seekclaw": "SeekClaw",
  "status.online": "Ühendatud",
  "status.offline": "Ühenduseta",
  "status.degraded": "Piiratud",
  "status.unknown": "Teadmata",
  "status.idle": "Sidumata",
  "status.connecting": "Ühendan",
  "status.error": "Viga",
  "common.retry": "Proovi uuesti",
  "common.repair": "Seo uuesti",
  "common.automatic": "Automaatne",
  "common.requiresApproval": "Vajab sinu kinnitust",
  "common.clear": "Puhasta",
  "common.reconnect": "Ühenda uuesti",
  "connection.gatewayError": "Gateway viga",
  "connection.gatewayOffline": "Gateway pole ühendatud",
  "connection.paused": "Reaalaja andmed on pausil, kuni gateway on jälle kättesaadav.",
  "connection.connectingTo": "Ühendan gatewayga {name}…",
  "pair.kicker": "CLAW Bridge",
  "pair.title": "Seo rakendus Termuxi gatewayga",
  "pair.description": "Sisesta gateway aadress ja ühekordne sidumiskood, mille näitab sinu seadmes käsk claw pair.",
  "pair.gatewayUrl": "Gateway aadress",
  "pair.gatewayHint": "Gateway LAN-aadress või Tailscale'i hostinimi.",
  "pair.gatewayInvalid": "Aadress peab algama http://, https://, ws:// või wss://",
  "pair.token": "Sidumiskood",
  "pair.tokenHint": "Salvestatakse ainult sellesse seadmesse.",
  "pair.failed": "Ühendamine ebaõnnestus",
  "pair.connected": "Ühendatud",
  "pair.opening": "Seotud gatewayga {name}. Avan töölaua…",
  "pair.testing": "Kontrollin ühendust…",
  "pair.connect": "Ühenda",
  "pair.recent": "Hiljutised gatewayd",
  "pair.recentHint": "Puuduta, et kasutada salvestatud ühendust.",
  "theme.title": "Välimus",
  "theme.description": "Vali CLAW-i kuvaprofiil ise. Automaatne režiim on valikuline ega ole vaikimisi kasutusel.",
  "theme.claw-red": "CLAW-i vaikimisi punane kujundus tavakasutuseks.",
  "theme.night-ops": "Roheline terminalistiil pimedasse ruumi.",
  "theme.amber-terminal": "Soe merevaigukollane kujundus öiseks kasutamiseks.",
  "theme.daylight": "Hele taust ja tugev kontrast ereda päevavalguse jaoks.",
  "theme.oled-black": "Täiesti must taust minimaalse helendusega AMOLED-ekraanile.",
  "theme.auto": "Valikuline süsteemipõhine vahetus. Käsitsi valitud teemad jäävad põhiliseks.",
  "dashboard.refresh": "Värskenda olekut",
  "dashboard.gateway": "Gateway",
  "dashboard.termux": "Termux",
  "dashboard.androidDevice": "Android-seade",
  "dashboard.charging": "laeb",
  "dashboard.activeRuns": "Aktiivsed tööd",
  "dashboard.pendingApprovals": "Ootel kinnitused",
  "dashboard.seekclawHint": "Leia töö · hinda sobivust · tee lokaalselt · kinnita välised tegevused",
  "dashboard.newCommand": "Uus käsk",
  "dashboard.lastHeartbeat": "Viimane ühendussignaal {time}",
  "seek.marketplace": "Agentide tööturg",
  "seek.agent": "SeekClaw agent",
  "seek.agentOnline": "Agent töötab",
  "seek.bridgeOffline": "Bridge ühenduseta",
  "seek.available": "Saadaval",
  "seek.matching": "Sobivad",
  "seek.active": "Aktiivsed",
  "seek.credits": "Krediidid",
  "seek.reputation": "Maine",
  "seek.findWork": "Otsi tööd",
  "seek.activeJobs": "Aktiivsed tööd",
  "seek.earnings": "Teenistus",
  "seek.pipeline": "Autonoomne töövoog",
  "seek.pipelineHint": "Lokaalne töö käib automaatselt. Välised ja tasulised tegevused peatuvad CLAW-i kinnituse juures.",
  "seek.findSuitable": "Leia sobiv töö",
  "seek.evaluate": "Hinda võimekust ja sobivust",
  "seek.apply": "Kandideeri tööle",
  "seek.build": "Codex / Claude teeb töö lokaalselt",
  "seek.tests": "Käivita lokaalsed testid",
  "seek.remote": "Windowsi / serveri kaugmuudatused",
  "seek.submit": "Esita lõpptulemus",
  "seek.creditSpending": "Krediitide kasutamine",
  "seek.selectedJob": "Valitud töö",
  "seek.selectedHint": "Kleebi SeekClaw töö ID. Kandideerimine ja välised tegevused jäävad CLAW-i kinnituse taha.",
  "seek.jobId": "SeekClaw töö ID",
  "seek.applyApproval": "Kandideeri kinnitusega",
  "seek.workLocally": "Tee töö lokaalselt",
  "seek.test": "Testi",
  "seek.stage": "Valmista tulemus ette",
  "seek.output": "Agendi väljund",
  "seek.outputHint": "Viimane SeekClaw / Codex tegevus",
  "seek.connectCli": "Ühenda SeekClaw CLI lokaalses keskkonnas ja värskenda vaadet.",
  "seek.reading": "Loen SeekClaw profiili ja avatud töid…",
  "seek.findFailed": "Tööde otsimine ebaõnnestus",
  "seek.applicationWaiting": "Kandideerimine ootab CLAW-i kinnitust enne SeekClaw'le saatmist.",
  "seek.applicationDone": "Kandideerimise käsk lõpetati.",
  "seek.applicationFailed": "Kandideerimine ebaõnnestus",
  "seek.workFailed": "Lokaalne töö ebaõnnestus",
  "seek.testsFailed": "Testid ebaõnnestusid",
  "seek.stageFailed": "Tulemuse ettevalmistamine ebaõnnestus",
  "seek.stagedNotice": "Tulemus on lokaalselt ette valmistatud. SeekClaw dokumentatsioonis pole praegu kinnitatud lõpliku töö esitamise endpointi, seega CLAW ei hakka seda välja mõtlema.",
  "chat.ask": "Küsi",
  "chat.once": "Üks kord",
  "chat.default": "Vaikimisi",
  "chat.currentContext": "Praegune kontekst",
  "chat.sharedMemory": "CLAW-i ühismälu",
  "chat.refreshContext": "Värskenda ühiskonteksti",
  "chat.noBranch": "branch puudub",
  "chat.goal": "Eesmärk",
  "chat.noGoal": "Projekti eesmärki pole veel salvestatud. Salvesta plaan ja kõik agendid saavad selle automaatselt.",
  "chat.latestFrom": "Viimane tulemus: {executor}",
  "chat.changedFiles": "Muudetud faile: {count}",
  "chat.agentOutput": "Agendi väljund",
  "chat.gatewayOffline": "Gateway ühenduseta",
  "chat.sharedReady": "Ühiskontekst valmis",
  "chat.reconnectContinue": "Jätkamiseks taasta ühendus.",
  "chat.readyHint": "Tee siin plaan ja saada see Codexile või Claude'ile koos olemasoleva kontekstiga.",
  "chat.sendTo": "Saada",
  "chat.permission": "Luba",
  "chat.placeholder": "Kirjuta plaan siia. CLAW annab ühiskonteksti valitud agendile kaasa.",
  "chat.savePlan": "Salvesta plaan",
  "chat.stop": "Peata",
  "chat.sendContext": "Saada kontekstiga",
  "chat.clearOutput": "Puhasta väljund",
  "chat.planSaved": "Plaan salvestati CLAW-i mällu",
  "chat.runStopped": "Töö peatati",
  "approvals.denied": "Keelatud",
  "approvals.allowedOnce": "Lubatud üks kord",
  "approvals.alwaysAllowed": "Alati lubatud",
  "approvals.justNow": "just nüüd",
  "approvals.minutesAgo": "{count} min tagasi",
  "approvals.hoursAgo": "{count} h tagasi",
  "approvals.daysAgo": "{count} p tagasi",
  "approvals.risk": "risk: {level}",
  "approvals.requested": "Küsitud {time}",
  "approvals.deny": "Keela",
  "approvals.allowOnce": "Luba üks kord",
  "approvals.alwaysAllow": "Luba alati",
  "approvals.pending": "Ootel",
  "approvals.audit": "Otsuste ajalugu",
  "approvals.loadFailed": "Kinnituste laadimine ebaõnnestus",
  "approvals.none": "Midagi pole kinnitada",
  "approvals.newHere": "Agentide uued kinnitustaotlused ilmuvad siia.",
  "approvals.syncLater": "Kinnitused sünkroonitakse, kui gateway on jälle ühendatud.",
  "approvals.noDecisions": "Otsuseid veel pole",
  "approvals.recorded": "Kõik lubamised ja keelamised salvestatakse siia.",
  "terminal.sessions": "Sessioonid",
  "terminal.close": "Sulge {name}",
  "terminal.newSession": "Uus sessioon",
  "terminal.noSession": "Sessiooni pole",
  "terminal.createSession": "Kirjutamise alustamiseks loo sessioon.",
  "terminal.running": "töötab",
  "terminal.input": "Terminali sisend",
  "terminal.typeCommand": "kirjuta käsk",
  "terminal.gatewayOffline": "gateway ühenduseta",
  "terminal.send": "Saada",
  "terminal.previous": "Eelmine käsk",
  "terminal.next": "Järgmine käsk",
  "terminal.reconnected": "Sessioon ühendati uuesti",
  "terminal.history": "Ajalugu",
  "terminal.commandHistory": "Käskude ajalugu",
  "biometric.locked": "CLAW Bridge on lukus",
  "biometric.hint": "Jätkamiseks kasuta ekraanilukku või sõrmejälge.",
  "biometric.checking": "Kontrollin…",
  "biometric.unlock": "Ava",
  "settings.gateway": "Gateway",
  "settings.pairedWith": "Seotud gatewayga {name}",
  "settings.notPaired": "Sidumata",
  "settings.gatewayUrl": "Gateway aadress",
  "settings.gatewayChangeHint": "Aadressi muutmisel tuleb rakendus uuesti siduda.",
  "settings.urlSaved": "Gateway aadress salvestati. Rakendamiseks seo uuesti.",
  "settings.telegram": "Telegrami bot",
  "settings.telegramHint": "Kaugteavitused ja käsud",
  "settings.termuxApi": "Termux:API",
  "settings.termuxApiHint": "Seadme sensorid, lõikelaud ja teavitused",
  "settings.shizuku": "Shizuku",
  "settings.shizukuHint": "Kõrgemad ADB-taseme õigused",
  "settings.security": "Turvalisus ja teavitused",
  "settings.biometric": "Biomeetriline lukk",
  "settings.biometricHint": "Rakenduse avamiseks nõua Androidi ekraanilukku või sõrmejälge.",
  "settings.biometricEnabled": "Biomeetriline lukk on sisse lülitatud",
  "settings.notifications": "Teavitused",
  "settings.notificationsHint": "Teavita uutest kinnitustaotlustest ja lõpetatud töödest.",
  "settings.permissions": "Vaikimisi load",
  "settings.permissionsHint": "Uute käskude eelseadistatud valikud.",
  "settings.defaultTarget": "Vaikimisi sihtmärk",
  "settings.defaultMode": "Vaikimisi loarežiim",
  "settings.askEvery": "Küsi iga kord",
  "settings.allowOnce": "Luba üks kord",
  "settings.projectDefault": "Projekti vaikeseade",
  "settings.autoAllow": "Luba madal risk automaatselt",
  "settings.autoAllowHint": "Ära küsi kinnitust ainult lugemist tegevatele käskudele.",
  "settings.backup": "Varukoopia",
  "settings.backupHint": "Tokeneid ekspordifaili ei lisata.",
  "settings.export": "Ekspordi JSON",
  "settings.import": "Impordi JSON",
  "settings.unpair": "Eemalda sidumine",
  "settings.unpaired": "Gateway sidumine eemaldati"
}

const DICTIONARY: Record<AppLanguage, Record<string, string>> = { et: ET, en: EN }

function format(template: string, vars?: Vars) {
  if (!vars) return template
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(vars[key] ?? `{${key}}`))
}

interface LanguageContextValue {
  language: AppLanguage
  setLanguage: (language: AppLanguage) => void
  t: (key: string, vars?: Vars) => string
}

const LanguageContext = React.createContext<LanguageContextValue | null>(null)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = React.useState<AppLanguage>("en")

  React.useEffect(() => {
    let next: AppLanguage = navigator.language.toLowerCase().startsWith("et") ? "et" : "en"
    try {
      const stored = window.localStorage.getItem(STORAGE_KEY)
      if (stored === "et" || stored === "en") next = stored
    } catch {}
    setLanguageState(next)
    document.documentElement.lang = next
  }, [])

  const setLanguage = React.useCallback((next: AppLanguage) => {
    setLanguageState(next)
    document.documentElement.lang = next
    try { window.localStorage.setItem(STORAGE_KEY, next) } catch {}
  }, [])

  const t = React.useCallback((key: string, vars?: Vars) => {
    const value = DICTIONARY[language][key] ?? EN[key] ?? key
    return format(value, vars)
  }, [language])

  const value = React.useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t])
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = React.useContext(LanguageContext)
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider")
  return context
}
